backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "assets/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: 'homepage'
    label: 'Homepage'
    files:
      - label: 'Homepage'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'text' }
          - { label: 'Layout', name: 'layout', widget: 'hidden'}
          - { label: 'Headline', name: 'headline', widget: 'text' }
          - { label: 'Lead Text', name: 'lead', widget: 'markdown' }
          - { label: 'Lead Image', name: 'titleImageUrl', widget: 'image' }
          - { label: 'About Heading', name: 'aboutHeading', widget: 'text' }
          - { label: 'About Lead', name: 'aboutLead', widget: 'text' }
          - { label: 'About Text', name: 'body', widget: 'markdown' }
      - label: 'Index Images'
        name: 'index_images'
        file: '_data/index_images.yml'
        fields:
          - label: 'Image Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'url', widget: 'image' }
      - label: 'Youtube Videos'
        name: 'youtube_videos'
        file: '_data/youtube_videos.yml'
        fields:
          - label: 'YT Video Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Url', name: 'url', widget: 'string' }
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Impressum'
        name: 'impressum'
        file: 'impressum.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden'}
          - { label: 'Layout', name: 'layout', widget: 'hidden'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Datenschutz'
        name: 'datenschutz'
        file: 'datenschutz.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden'}
          - { label: 'Layout', name: 'layout', widget: 'hidden'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'releases'
    label: 'Releases'
    folder: '_releases/'
    create: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Cover', name: 'cover', widget: 'image' }
      - { label: 'Text', name: 'body', widget: 'markdown' }
  - name: 'epk'
    label: 'EPK'
    files:
      - label: 'EPK'
        name: 'epk'
        file: 'epk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'text' }
          - { label: 'Layout', name: 'layout', widget: 'hidden'}
          - { label: 'Headline', name: 'headline', widget: 'text' }
          - { label: 'Lead Text', name: 'lead', widget: 'markdown' }
          - { label: 'Lead Image', name: 'titleImageUrl', widget: 'image' }
          - { label: 'About Heading', name: 'aboutHeading', widget: 'text' }
          - { label: 'About Lead', name: 'aboutLead', widget: 'text' }
          - { label: 'About Text', name: 'body', widget: 'markdown' }
      - label: 'EPK Images'
        name: 'epk_images'
        file: '_data/epk_images.yml'
        fields:
          - label: 'Image Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'url', widget: 'image' }
